name: Run Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run bundler install
        run: bundle install
      -
        name: Run Tests
        run: rspec spec --format documentation --color
